import 'package:easy_localization/easy_localization.dart';
import 'package:fitness/model/muscle_groups.dart';
import 'package:fitness/model/workout_model.dart';
import 'package:fitness/utils/words.dart';

List<WorkOutModel> initiateStartup(){
  return [
    WorkOutModel(name: diamondPushUps.tr(), difficulty: 5, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 1),
    WorkOutModel(name: kneelingDiamondPushUps.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 2),
    WorkOutModel(name: explosivePushUps.tr(), difficulty: 5, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 3),
    WorkOutModel(name: benchDips.tr(), difficulty: 3, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 4),
    WorkOutModel(name: pushUps.tr(), difficulty: 4, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 5),
    WorkOutModel(name: inclinePushUps.tr(), difficulty: 3, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 6),
    WorkOutModel(name: assistedPushUps.tr(), difficulty: 1, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 7),
    WorkOutModel(name: oneArmPushUps.tr(), difficulty: 5, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], additionalInfo: perArm.tr(), id: 8),
    WorkOutModel(name: elevatedPushUps.tr(), difficulty: 5, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 10),
    WorkOutModel(name: kneeTouchPushUps.tr(), difficulty: 5, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], additionalInfo: perSide.tr(), id:  11),
    WorkOutModel(name: wideGripPushUps.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.absGroup], id: 12),
    WorkOutModel(name: wideGripInclinePushUps.tr(), difficulty: 2, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup], id: 13),
    WorkOutModel(name: sidePlank.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.buttocksGroup], additionalInfo: perSide.tr(), id: 14),
    WorkOutModel(name: bicycle.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], id: 15),
    WorkOutModel(name: verticalScissors.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup], id: 16),
    WorkOutModel(name: sidePlankWithHipDips.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.buttocksGroup], additionalInfo: perSide.tr(), id: 17),
    WorkOutModel(name: lateralLegRaises.tr(), difficulty: 4, muscleGroups: [MuscleGroups.absGroup, MuscleGroups.buttocksGroup], additionalInfo: perSide.tr(), id: 18),
    WorkOutModel(name: oneArmPlankWithRotations.tr(), difficulty: 4, muscleGroups: [MuscleGroups.absGroup, MuscleGroups.buttocksGroup], additionalInfo: perSide.tr(), id: 19),
    WorkOutModel(name: reverseHipThrusts.tr(), difficulty: 4, muscleGroups: [MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.absGroup], id: 20),
    WorkOutModel(name: abSkiing.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 21),
    WorkOutModel(name: heelTouch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.absGroup], additionalInfo: perSide.tr(), id: 22),
    WorkOutModel(name: crossBodyCrunches.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], additionalInfo: perSide.tr(), id: 23),
    WorkOutModel(name: scissors.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup], id: 24),
    WorkOutModel(name: bottomsUp.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup], id: 25),
    WorkOutModel(name: plankUpper.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.buttocksGroup, MuscleGroups.backGroup], id: 26),
    WorkOutModel(name: oneArmPlankWithKneeTouches.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.shouldersGroup, MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perSide.tr(), id: 27),
    WorkOutModel(name: fullExtensionPlank.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.absGroup ], id: 28),
    WorkOutModel(name: plankJacks.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup, MuscleGroups.backGroup ], id: 29),
    WorkOutModel(name: lyingLegRotations.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup],additionalInfo: perSide.tr(), id: 30),
    WorkOutModel(name: bendLegTwists.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], id: 31),
    WorkOutModel(name: highFiveCrunches.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.shouldersGroup], id: 32),
    WorkOutModel(name: bentKneeLegRaises.tr(), difficulty: 3, muscleGroups: [MuscleGroups.absGroup], id: 33),
    WorkOutModel(name: sitUpsHigher.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.absGroup], id: 34),
    WorkOutModel(name: lyingLegRaises.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup ], id: 35),
    WorkOutModel(name: crossArmCrunches.tr(), difficulty: 4, muscleGroups: [MuscleGroups.absGroup ], id: 36),
    WorkOutModel(name: boatPose.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup], id: 37),
    WorkOutModel(name: unilateralLyingLegRaises.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup ], id: 38),
    WorkOutModel(name: advancedLyingLegRaises.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup], id: 39),
    WorkOutModel(name: helloDarlings.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup ], id: 40),
    WorkOutModel(name: russianTwists.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], additionalInfo: perSide.tr(), id: 41),
    WorkOutModel(name: mountainClimber.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup], id: 42),
    WorkOutModel(name: crunches.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.absGroup], additionalInfo: perSide.tr(), id: 43),
    WorkOutModel(name: obliqueCrunches.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], additionalInfo: perSide.tr(), id: 44),
    WorkOutModel(name: elevatedLegCrunches.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], id: 45),
    WorkOutModel(name: raisedLegCrunches.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], id: 46),
    WorkOutModel(name: abdominalCocoons.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], id: 47),
    WorkOutModel(name: jumpingLegTucks.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup ], id: 48),
    WorkOutModel(name: vUps.tr(), difficulty: 5, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup], id: 49),
    WorkOutModel(name: vTwisting.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup], additionalInfo: perSide.tr(), id: 50),
    WorkOutModel(name: reverseCrunchesWithClaps.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], id: 51),
    WorkOutModel(name: plankStar.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup], id: 52),
    WorkOutModel(name: plankWithAlternateLegLift.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.buttocksGroup ], id: 53),
    WorkOutModel(name: staticBicycle.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup], id: 54),
    WorkOutModel(name: straightArmSidePlank.tr(), difficulty: 5, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.shouldersGroup, MuscleGroups.armsGroup], additionalInfo: perSide.tr(), id: 55),
    WorkOutModel(name: seatedBicycleCrunch.tr(), difficulty: 5, muscleGroups: [ MuscleGroups.absGroup], id: 56),
    WorkOutModel(name: legsPushing.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup], id: 57),
    WorkOutModel(name: sideLunges.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perSide.tr(), id: 58),
    WorkOutModel(name: jumpSquats.tr(), difficulty: 4, muscleGroups: [MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 59),
    WorkOutModel(name: alternatingJumpLunges.tr(), difficulty: 4, muscleGroups: [MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 60),
    WorkOutModel(name: forwardLunges.tr(), difficulty: 3, muscleGroups: [MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 61),
    WorkOutModel(name: backwardLunges.tr(), difficulty: 3, muscleGroups: [MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 62),
    WorkOutModel(name: jumpingLunges.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 63),
    WorkOutModel(name: deepSquatsHigher.tr(), difficulty: 4, muscleGroups: [  MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 64),
    WorkOutModel(name: gluteKickbacks.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 65),
    WorkOutModel(name: singleLegStiffLeggedDeadlifts.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup, MuscleGroups.backGroup ], additionalInfo: perLeg.tr(), id: 66),
    WorkOutModel(name: unilateralCalfRaises.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.legsGroup], id: 67),
    WorkOutModel(name: staticSquats.tr(), difficulty: 3, muscleGroups: [MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 68),
    WorkOutModel(name: forwardLeaps.tr(), difficulty: 5, muscleGroups: [MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 69),
    WorkOutModel(name: verticalCalfJumps.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.legsGroup], id: 70),
    WorkOutModel(name: gluteBridge.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup, MuscleGroups.backGroup ], id: 71),
    WorkOutModel(name: plieSquatWithKneeUps.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 73),
    WorkOutModel(name: backwardLunges.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 74),
    WorkOutModel(name: singleLegGluteBridge.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup, MuscleGroups.backGroup ], additionalInfo: perLeg.tr(), id: 75),
    WorkOutModel(name: bulgarianSplitSquats.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 77),
    WorkOutModel(name: highKneesHigher.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup], id: 78),
    WorkOutModel(name: burpees.tr(), difficulty: 5, muscleGroups: [ MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 79),
    WorkOutModel(name: lateralBurpees.tr(), difficulty: 5, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup ], id: 80),
    WorkOutModel(name: swingingHighKicks.tr(), difficulty: 1, muscleGroups: [MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup ], additionalInfo: perLeg.tr(), id: 84),
    WorkOutModel(name: forwardLungeStretch.tr(), difficulty: 1, muscleGroups: [MuscleGroups.absGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup ], additionalInfo: perLeg.tr(), id:85),
    WorkOutModel(name: lateralJumps.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 86),
    WorkOutModel(name: squatReaches.tr(), difficulty: 3, muscleGroups: [MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], additionalInfo: perSide.tr(), id: 87),
    WorkOutModel(name: standingLatsStretch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.backGroup], additionalInfo: perSide.tr(), id: 88),
    WorkOutModel(name: standingToeTouch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup, MuscleGroups.backGroup], id: 89),
    WorkOutModel(name: cobraStretch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.absGroup ], id: 92),
    WorkOutModel(name: childsPose.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.backGroup], id: 93),
    WorkOutModel(name: jumpingJacks.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.shouldersGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup ], id: 94),
    WorkOutModel(name: lyingGlutStretch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 95),
    WorkOutModel(name: lyingHamstringStretch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.buttocksGroup, MuscleGroups. legsGroup], additionalInfo: perLeg.tr(), id: 96),
    WorkOutModel(name: standingQuadricepsStretch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.legsGroup], additionalInfo: perLeg.tr(), id: 97),
    WorkOutModel(name: elevatedStandingToeTouch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.legsGroup], additionalInfo: perLeg.tr(), id: 98),
    WorkOutModel(name: standingBehindTheNeckStretch.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.armsGroup], additionalInfo: perArm.tr(), id: 99),
    WorkOutModel(name: superman.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.shouldersGroup, MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 100),
    WorkOutModel(name: reverseFlutterKicks.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup, MuscleGroups.backGroup ], id: 101),
    WorkOutModel(name: spidermanSteps.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.absGroup ], id: 102),
    WorkOutModel(name: shadowBoxingWhileTunningInPlace.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.legsGroup ], id: 103),
    WorkOutModel(name: lumberjack.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.armsGroup, MuscleGroups.absGroup, MuscleGroups.shouldersGroup, MuscleGroups.legsGroup], additionalInfo: perSide.tr(), id: 104),
    WorkOutModel(name: sideLegLifts.tr(), difficulty: 2, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.legsGroup], id: 105),
    WorkOutModel(name: plankWalkups.tr(), difficulty: 5, muscleGroups: [ MuscleGroups.chestGroup, MuscleGroups.armsGroup, MuscleGroups.shouldersGroup, MuscleGroups.absGroup ], id: 106),
    WorkOutModel(name: sideLegRaises.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.absGroup, MuscleGroups.buttocksGroup], additionalInfo: perLeg.tr(), id: 107),
    WorkOutModel(name: starJumps.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.legsGroup, MuscleGroups.buttocksGroup], id: 108),
    WorkOutModel(name: calfRaises.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.legsGroup], id: 110),
    WorkOutModel(name: elbowToKneeDitUps.tr(), difficulty: 3, muscleGroups: [ MuscleGroups.absGroup], additionalInfo: perSide.tr(), id: 111),
    WorkOutModel(name: standingKneeFlexions.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.legsGroup], additionalInfo: perLeg.tr(), id: 112),
    WorkOutModel(name: bentKneeCalfRaises.tr(), difficulty: 1, muscleGroups: [ MuscleGroups.legsGroup], additionalInfo: perLeg.tr(), id: 113),
    WorkOutModel(name: advancedBentKneeLegRaises.tr(), difficulty: 4, muscleGroups: [ MuscleGroups.absGroup], id: 114),
  ];
}